# Generated by Django 4.1.7 on 2023-03-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MuseumTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titel', models.CharField(max_length=40)),
                ('Manufacturer', models.CharField(max_length=40)),
                ('Factual_text', models.CharField(max_length=400)),
                ('Description', models.CharField(max_length=800)),
                ('Long_Description', models.CharField(blank=True, max_length=800)),
                ('Picture1_path', models.CharField(blank=True, max_length=40)),
                ('Picture2_path', models.CharField(blank=True, max_length=40)),
                ('Picture3_path', models.CharField(blank=True, max_length=40)),
            ],
        ),
    ]
